### ISSUE TITLE
Trouble Installing 

### ISSUE THREAD

**Issue by baduk4** [terrencetec/kontrol#40]
Hello,

I have followed the [instructions for installing the Kontrol library](https://kontrol.readthedocs.io/en/latest/getting_started.html) and am having some trouble.

I first open a terminal window and type:
`conda install -c conda-forge numpy scipy matplotlib control ezca`

I then type:
 git clone https://github.com/terrencetec/kontrol.git
 cd kontrol
 pip install .

The output in the terminal window is the following:
```
Processing/home/baduk/Documents/Engineering/Python/Python Scripts/kontrol
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /home/baduk/anaconda3/lib/python3.9/site-packages (from kontrol==1.1.0) (1.21.5)
Requirement already satisfied: scipy in /home/baduk/anaconda3/lib/python3.9/site-packages (from kontrol==1.1.0) (1.5.3)
Requirement already satisfied: matplotlib in /home/baduk/anaconda3/lib/python3.9/site-packages (from kontrol==1.1.0) (3.5.1)
Requirement already satisfied: control>=0.9 in /home/baduk/anaconda3/lib/python3.9/site-packages (from kontrol==1.1.0) (0.9.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (4.25.0)
Requirement already satisfied: pillow>=6.2.0 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (9.2.0)
Requirement already satisfied: cycler>=0.10 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (1.4.2)
Requirement already satisfied: pyparsing>=2.2.1 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (3.0.4)
Requirement already satisfied: packaging>=20.0 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (21.3)
Requirement already satisfied: six>=1.5 in /home/baduk/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib->kontrol==1.1.0) (1.16.0)
Building wheels for collected packages: kontrol
  Building wheel for kontrol (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      /home/baduk/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'extra_requires'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      /home/baduk/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      installing to build/bdist.linux-x86_64/wheel
      running install
      running install_lib
      creating build/bdist.linux-x86_64/wheel
      error: could not create 'build/bdist.linux-x86_64/wheel': Permission denied
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for kontrol
  Running setup.py clean for kontrol
Failed to build kontrol
Installing collected packages: kontrol
  Running setup.py install for kontrol ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for kontrol did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      /home/baduk/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'extra_requires'
        warnings.warn(msg)
      running install
      /home/baduk/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running install_lib
      running install_egg_info
      running egg_info
      error: [Errno 13] Permission denied
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> kontrol

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

````
It is not clear why I am having trouble installing the library, and would appreciate any suggestions.

**Comment by terrencetec** [comment]
I am not sure why it happens.
I tried cloning the repository and installing `kontrol` in a new conda environment and the base environment.
They both worked flawlessly.
It might not help but it's worth trying to install the package in a new conda environment.
The following is what I did.
```
conda create -n kontrol
conda install -c conda-forge numpy scipy matplotlib control
# In the control directory
pip install .
```

I also googled some of the error messages you posted and it pointed toward some issues with Windows Subsystems for Linux.
By any chance, you are using WSL?
If so, check the following
https://github.com/pypa/packaging-problems/issues/258#issuecomment-514934944
https://askubuntu.com/questions/1129782/running-python3-setup-py-bdist-wheel-on-a-mnt-c-path-results-in-a-errno

**Comment by baduk4** [comment]
Thank you for your reply.  I ran the commands that you mention in your reply and the result is the following:

```
Processing /home/baduk/Documents/Engineering/Python/Python Scripts/kontrol
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /home/baduk/anaconda3/lib/python3.9/site-packages (from kontrol==1.1.0) (1.21.5)
Requirement already satisfied: scipy in /home/baduk/anaconda3/lib/python3.9/site-packages (from kontrol==1.1.0) (1.5.3)
Requirement already satisfied: matplotlib in /home/baduk/anaconda3/lib/python3.9/site-packages (from kontrol==1.1.0) (3.5.1)
Requirement already satisfied: control>=0.9 in /home/baduk/anaconda3/lib/python3.9/site-packages (from kontrol==1.1.0) (0.9.2)
Requirement already satisfied: cycler>=0.10 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (3.0.4)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (1.4.2)
Requirement already satisfied: pillow>=6.2.0 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (9.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (2.8.2)
Requirement already satisfied: packaging>=20.0 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (21.3)
Requirement already satisfied: fonttools>=4.22.0 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (4.25.0)
Requirement already satisfied: six>=1.5 in /home/baduk/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib->kontrol==1.1.0) (1.16.0)
Building wheels for collected packages: kontrol
  Building wheel for kontrol (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      /home/baduk/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'extra_requires'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      /home/baduk/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      installing to build/bdist.linux-x86_64/wheel
      running install
      running install_lib
      creating build/bdist.linux-x86_64/wheel
      error: could not create 'build/bdist.linux-x86_64/wheel': Permission denied
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for kontrol
  Running setup.py clean for kontrol
Failed to build kontrol
Installing collected packages: kontrol
  Running setup.py install for kontrol ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for kontrol did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      /home/baduk/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'extra_requires'
        warnings.warn(msg)
      running install
      /home/baduk/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running install_lib
      running install_egg_info
      running egg_info
      error: [Errno 13] Permission denied
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> kontrol

note: This is an issue with the package mentioned above, not pip.
```
I am not using WSL.  I am using Ubuntu version 20.04.  I do have Wine installed for programs that need Windows.

**Comment by terrencetec** [comment]
Have you run `sudo` in the repository directory before?

`error: could not create 'build/bdist.linux-x86_64/wheel': Permission denied`
`error: [Errno 13] Permission denied`
^
These two lines seem to me you tried to install the package with root privilege but failed and created files/directories that your user cannot access.
Could you clone a fresh repository and try again?

**Comment by baduk4** [comment]
A partial success

```
(base) baduk@baduk-ThinkPad-W540:~/Documents/Engineering/Python$ conda create -n kontrol
WARNING: A conda environment already exists at '/home/baduk/anaconda3/envs/kontrol'
Remove existing environment (y/[n])? y

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/baduk/anaconda3/envs/kontrol



Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate kontrol
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Retrieving notices: ...working... done
(base) baduk@baduk-ThinkPad-W540:~/Documents/Engineering/Python$ conda install -c conda-forge numpy scipy matplotlib control
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Retrieving notices: ...working... done
(base) baduk@baduk-ThinkPad-W540:~/Documents/Engineering/Python$ ls
'Python Documents'  'Python Scripts'
(base) baduk@baduk-ThinkPad-W540:~/Documents/Engineering/Python$ git clone https://github.com/terrencetec/kontrol.git
Cloning into 'kontrol'...
remote: Enumerating objects: 2803, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 2803 (delta 0), reused 1 (delta 0), pack-reused 2798
Receiving objects: 100% (2803/2803), 89.31 MiB | 4.17 MiB/s, done.
Resolving deltas: 100% (1898/1898), done.
Updating files: 100% (222/222), done.
(base) baduk@baduk-ThinkPad-W540:~/Documents/Engineering/Python$ cd kontrol
(base) baduk@baduk-ThinkPad-W540:~/Documents/Engineering/Python/kontrol$ pip install .
Processing /home/baduk/Documents/Engineering/Python/kontrol
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /home/baduk/anaconda3/lib/python3.9/site-packages (from kontrol==1.1.0) (1.21.5)
Requirement already satisfied: scipy in /home/baduk/anaconda3/lib/python3.9/site-packages (from kontrol==1.1.0) (1.5.3)
Requirement already satisfied: matplotlib in /home/baduk/anaconda3/lib/python3.9/site-packages (from kontrol==1.1.0) (3.5.1)
Requirement already satisfied: control>=0.9 in /home/baduk/anaconda3/lib/python3.9/site-packages (from kontrol==1.1.0) (0.9.2)
Requirement already satisfied: packaging>=20.0 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (21.3)
Requirement already satisfied: cycler>=0.10 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (3.0.4)
Requirement already satisfied: pillow>=6.2.0 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (9.2.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (1.4.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in /home/baduk/anaconda3/lib/python3.9/site-packages (from matplotlib->kontrol==1.1.0) (4.25.0)
Requirement already satisfied: six>=1.5 in /home/baduk/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib->kontrol==1.1.0) (1.16.0)
Building wheels for collected packages: kontrol
  Building wheel for kontrol (setup.py) ... done
  Created wheel for kontrol: filename=kontrol-1.1.0-py3-none-any.whl size=64336 sha256=9dcd07df700f19a9828b91465a39225f4b73845abdb53afb6101c65479a20a1c
  Stored in directory: /tmp/pip-ephem-wheel-cache-n1yvuqbf/wheels/ca/5a/eb/0b76bc010b447726c030d735755da14ebf9d0c8072e6554b73
Successfully built kontrol
Installing collected packages: kontrol
Successfully installed kontrol-1.1.0
(base) baduk@baduk-ThinkPad-W540:~/Documents/Engineering/Python/kontrol$ 
```

This looks very good, but I tried running the code below:
```
import control
import numpy as np
import matplotlib.pyplot as plt
import kontrol.curvefit
import scipy.optimize

f = np.logspace(-3, 3, 100000)
s = 1j*2*np.pi*f
tf = (s**2 + 3*s + 2) / (s**3 + 12*s**2 + 47*s + 60)

plt.figure(figsize=(15, 5))
plt.subplot(121)
plt.loglog(f, abs(tf))
plt.grid(which="both")
plt.ylabel("Amplitude")
plt.xlabel("Frequency (Hz)")
plt.subplot(122)
plt.semilogx(f, np.angle(tf))
plt.grid(which="both")
plt.ylabel("Phase (rad)")
plt.xlabel("Frequency (Hz)")
plt.show()

xdata = f
ydata = tf
model = kontrol.curvefit.model.TransferFunctionModel(nzero=2, npole=3, log_args=False)
error_func = kontrol.curvefit.error_func.tf_error
cost = kontrol.curvefit.Cost(error_func=error_func)
optimizer = scipy.optimize.minimize
```

I tried running this code in several locations, but get the same error each time:
```
runfile('/home/baduk/Documents/Engineering/Python/meas_data_fit_220821.py', wdir='/home/baduk/Documents/Engineering/Python')
Traceback (most recent call last):

  File "/home/baduk/Documents/Engineering/Python/meas_data_fit_220821.py", line 4, in <module>
    import kontrol.curvefit

ModuleNotFoundError: No module named 'kontrol.curvefit'


runfile('/home/baduk/Documents/Engineering/Python/kontrol/meas_data_fit_220821.py', wdir='/home/baduk/Documents/Engineering/Python/kontrol')
Traceback (most recent call last):

  File "/home/baduk/Documents/Engineering/Python/kontrol/meas_data_fit_220821.py", line 4, in <module>
    import kontrol.curvefit

ModuleNotFoundError: No module named 'kontrol.curvefit'


runfile('/home/baduk/Documents/Engineering/Python/kontrol/meas_data_fit_220821.py', wdir='/home/baduk/Documents/Engineering/Python/kontrol')
Traceback (most recent call last):

  File "/home/baduk/Documents/Engineering/Python/kontrol/meas_data_fit_220821.py", line 4, in <module>
    import kontrol.curvefit

ModuleNotFoundError: No module named 'kontrol.curvefit'
```

**Comment by baduk4** [comment]
Success!  I restarted the editor (Spyder) and it produces an output without errors.

Thank you!

**Comment by terrencetec** [comment]
Nice, happy coding.
